apiVersion: v1
kind : Namespace
metadata:
    name: webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-webapp-deployment
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-webapp
  template:
    metadata:
      labels:
        app: spring-webapp
    spec:
      containers:
        - name: spring-webapp
          image: faixan01/spring-webapp:5  # Replace with your actual image tag
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata: 
  name: spring-webapp-service
  namespace : webapp
spec:
  type: NodePort
  selector:
    app: spring-webapp
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30036

